### PR TITLE
not much to change

### LINKED ISSUE #42: Implement UserCardsManager

### PR DESCRIPTION
**Pull request by idafum**
closes #42

### CODE REVIEW

**Comment by VanJackal** [comment]
what is this pr doing? why is it just removing the documentation on IUserCardsManager?

**Comment by idafum** [comment]
I just wanted to redo the userCardsManager but it looks fine.
Didnt really have to make another branch and pr

**Comment by VanJackal** [comment]
if its already implemented just close the issue

**Comment by idafum** [comment]
okay

**Pull request closed without merging**
